"""Deterministic alert models.

Alerts are generated by rule from validated deterministic results - never by an
LLM. Proxy / model-derived alerts are labelled as such and never described as
authoritative real-time detection.
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict


class AlertSeverity(str, Enum):
    INFO = "info"
    ADVISORY = "advisory"
    WARNING = "warning"
    CRITICAL = "critical"


class AlertKind(str, Enum):
    HIGH_WAVE = "high_wave"
    HIGH_WIND = "high_wind"
    THUNDERSTORM_PROXY = "thunderstorm_lightning_proxy"
    CYCLONE_PROXY = "cyclone_proxy"
    HARD_GEOFENCE = "hard_geofence"
    MISSING_CRITICAL_DATA = "missing_critical_data"
    STALE_DATA = "stale_data"
    SOURCE_CONFLICT = "source_conflict"
    ROUTE_BLOCKED = "route_blocked"
    NO_SAFE_RECOMMENDATION = "no_safe_recommendation"


class Alert(BaseModel):
    model_config = ConfigDict(frozen=True)

    kind: AlertKind
    severity: AlertSeverity
    message: str
    # "observed" | "model_derived" | "proxy"
    signal_kind: str = "model_derived"
    evidence_ids: tuple[str, ...] = ()
    deterministic: bool = True
