"""Deterministic Alert Engine.

Alerts are generated by rule from deterministic results. Thunderstorm/lightning
and cyclone alerts are explicitly labelled as model-derived proxies - never as
authoritative real-time detection.
"""

from __future__ import annotations

from app.models.alert import Alert, AlertKind, AlertSeverity
from app.models.conflict import Conflict, ConflictSeverity
from app.models.decision import DecisionResult, DecisionStatus
from app.models.fabric import MarineDataFabric, ValidityState
from app.models.gis_agent import GisQueryResult
from app.models.risk import FactorStatus, RiskLevel, RiskResult
from app.models.routing import RouteResult, RouteStatus

# ORCA engineering / MVP alert thresholds (not authoritative marine limits).
_WAVE_WARN_M = 2.5
_WAVE_CRIT_M = 3.5
_WIND_WARN_MS = 12.0
_WIND_CRIT_MS = 17.0
_THUNDERSTORM_CODES = frozenset({95, 96, 97, 98, 99})


def generate_alerts(
    *,
    risk: RiskResult | None,
    decision: DecisionResult | None,
    fabric: MarineDataFabric | None = None,
    gis: GisQueryResult | None = None,
    route: RouteResult | None = None,
    conflicts: tuple[Conflict, ...] = (),
) -> tuple[Alert, ...]:
    alerts: list[Alert] = []

    # ---- from fabric observations (deterministic thresholds) ----
    if fabric is not None:
        wave = fabric.first_value("wave_height")
        if wave is not None:
            if wave >= _WAVE_CRIT_M:
                alerts.append(_a(AlertKind.HIGH_WAVE, AlertSeverity.CRITICAL,
                                 f"Significant wave height {wave:.1f} m (critical threshold {_WAVE_CRIT_M} m).", "observed"))
            elif wave >= _WAVE_WARN_M:
                alerts.append(_a(AlertKind.HIGH_WAVE, AlertSeverity.WARNING,
                                 f"Significant wave height {wave:.1f} m (warning threshold {_WAVE_WARN_M} m).", "observed"))
        wind = fabric.first_value("wind_speed")
        if wind is not None:
            if wind >= _WIND_CRIT_MS:
                alerts.append(_a(AlertKind.HIGH_WIND, AlertSeverity.CRITICAL,
                                 f"Wind speed {wind:.1f} m/s (critical threshold {_WIND_CRIT_MS} m/s).", "observed"))
            elif wind >= _WIND_WARN_MS:
                alerts.append(_a(AlertKind.HIGH_WIND, AlertSeverity.WARNING,
                                 f"Wind speed {wind:.1f} m/s (warning threshold {_WIND_WARN_MS} m/s).", "observed"))
        code = fabric.first_value("weather_code")
        if code is not None and int(code) in _THUNDERSTORM_CODES:
            alerts.append(_a(
                AlertKind.THUNDERSTORM_PROXY, AlertSeverity.WARNING,
                f"Thunderstorm/lightning PROXY active (WMO weather code {int(code)}). "
                "This is a model-derived proxy, not strike-level lightning detection.",
                "proxy",
            ))
        stale = [
            r.variable for r in fabric.records if r.validity is ValidityState.STALE
        ]
        if stale:
            alerts.append(_a(
                AlertKind.STALE_DATA, AlertSeverity.ADVISORY,
                "Some evidence is stale and was not treated as current: " + ", ".join(sorted(set(stale))) + ".",
                "model_derived",
            ))

    # ---- from risk result ----
    if risk is not None:
        cyc = next((f for f in risk.factors if f.name == "cyclone_proxy"), None)
        if cyc is not None and cyc.status is FactorStatus.EVALUATED and (cyc.normalized_score or 0) > 0.3:
            alerts.append(_a(
                AlertKind.CYCLONE_PROXY, AlertSeverity.WARNING,
                "Model-derived cyclone PROXY signal is elevated. ORCA has no live "
                "authoritative RSMC cyclone feed; the RSMC bulletin is a reference snapshot.",
                "model_derived",
            ))
        if risk.missing_critical_factors:
            alerts.append(_a(
                AlertKind.MISSING_CRITICAL_DATA, AlertSeverity.CRITICAL,
                "Missing safety-critical data: " + ", ".join(risk.missing_critical_factors) + ".",
                "model_derived",
            ))
        if risk.risk_level is RiskLevel.SEVERE:
            alerts.append(_a(AlertKind.HIGH_WAVE, AlertSeverity.CRITICAL,
                             f"Deterministic marine risk is SEVERE (score {risk.overall_score:.0f}/100).",
                             "model_derived"))

    # ---- from GIS ----
    if gis is not None and gis.inside_hard_geofence:
        alerts.append(_a(
            AlertKind.HARD_GEOFENCE, AlertSeverity.CRITICAL,
            "Location is inside a hard geofence: " + ", ".join(gis.hard_geofence_ids) + ".",
            "observed",
        ))

    # ---- from decision ----
    if decision is not None:
        if decision.status is DecisionStatus.NO_SAFE_RECOMMENDATION:
            alerts.append(_a(
                AlertKind.NO_SAFE_RECOMMENDATION, AlertSeverity.CRITICAL,
                "ORCA cannot make a safe recommendation - required data is missing or unverified.",
                "model_derived",
            ))
        elif decision.status is DecisionStatus.DO_NOT_PROCEED:
            alerts.append(_a(
                AlertKind.NO_SAFE_RECOMMENDATION, AlertSeverity.CRITICAL,
                "ORCA recommends against proceeding under the current conditions.",
                "model_derived",
            ))

    # ---- from route ----
    if route is not None and route.status in (
        RouteStatus.NO_ROUTE, RouteStatus.DESTINATION_BLOCKED,
        RouteStatus.ORIGIN_BLOCKED, RouteStatus.ROUTE_VALIDATION_FAILED,
    ):
        alerts.append(_a(
            AlertKind.ROUTE_BLOCKED, AlertSeverity.WARNING,
            f"Route could not be provided ({route.status.value}).", "model_derived",
        ))

    # ---- from conflicts ----
    for c in conflicts:
        if c.severity is ConflictSeverity.SAFETY_CRITICAL:
            alerts.append(_a(
                AlertKind.SOURCE_CONFLICT,
                AlertSeverity.WARNING if c.resolution_status.value == "resolved" else AlertSeverity.CRITICAL,
                f"Source conflict on {c.variable}: {c.detail}", "model_derived",
                evidence_ids=c.evidence_ids,
            ))

    # de-dupe by (kind, message)
    seen: set[tuple[str, str]] = set()
    out: list[Alert] = []
    for a in alerts:
        key = (a.kind.value, a.message)
        if key not in seen:
            seen.add(key)
            out.append(a)
    return tuple(out)


def _a(kind, severity, message, signal_kind, *, evidence_ids=()) -> Alert:  # type: ignore[no-untyped-def]
    return Alert(
        kind=kind, severity=severity, message=message,
        signal_kind=signal_kind, evidence_ids=tuple(evidence_ids),
    )
